[package]
name = "mtt"
version = "0.1.0"
authors = ["Mikhail Zharkov"]

[dependencies]
criterion = "0.2"
vmt = { path = "../vector-merkle-tree" }
ring = "^0.13.0"
rand = "0.6.0"

[[bench]]
name = "benchmark"
harness = false